services:

  api-gateway:
    build:
      context: ./../api-gateway
      dockerfile: ./../api-gateway/api-gateway.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authApp.dockerfile
    restart: always
    ports:
      - "8080"
    deploy:
      mode: replicated
      replicas: 1

  postgres-auth:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./sql/auth:/docker-entrypoint-initdb.d
      - ./db-data/auth-data/:/var/lib/postgresql/data